name: Compatibility verification between PyMoDAQ and plugins

on:
  schedule:
    - cron: '0 15 * * 0'  # Runs at 3pm UTC on Sunday
  workflow_dispatch:

jobs:
  check-compatibility:
    strategy:
      fail-fast: false
      matrix:
        pymodaq-version: ["4.4.x", "latest"] # latest is not a real branch / version name 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-cursor0 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils libgl1 libegl1
          export QT_DEBUG_PLUGINS=1

          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install hatch pyqt5
          if [[ "${{ matrix.pymodaq-version }}" = "latest" ]]; then
            pip install git+https://github.com/PyMoDAQ/PyMoDAQ.git
          else
            pip install git+https://github.com/PyMoDAQ/PyMoDAQ.git@${{ matrix.pymodaq-version }}
          fi
          
      - name: Run script
        run: |
          source venv/bin/activate
          python src/pymodaq_plugin_manager/compatibility_checker.py "git+https://github.com/PyMoDAQ/PyMoDAQ.git@${{ matrix.pymodaq-version }}"

      - name: Upload reports if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-reports-${{ matrix.pymodaq-version }}
          path: reports

      - name: Check version
        if: always()
        run: |
          cd ${GITHUB_WORKSPACE}
          source venv/bin/activate
          pip list